name: deploy

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Install tree
        run: |
          sudo apt-get install tree
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create build folder
        run: |
          mkdir dist && cp -r notes/* dist 
      - name: Generate tree
        run: |
          cd dist && tree -H . -I 'index.html' -D --timefmt='%b %d %Y %R' --charset utf-8 -T 'mit-notes' > index.html && cd .. 
      - name: Archive build folder
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  deploy:
    permissions: 
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download build folder
        uses: actions/download-artifact@v3
        with: 
          name: dist
          path: dist
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5 
        with:
          branch: gh-pages
          folder: dist 
