name: deploy

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Generate tree
        run: |
          tree -H . -I 'index.html' -D --timefmt='%b %d %Y %R' --charset utf-8 -T 'mit-notes' > index.html
  deploy:
    permissions: 
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Deploy
        uses: actions/deploy-pages@v2
