name: deploy

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Create build folder
        run: |
          mkdir dist
      - name: Generate tree
        run: |
          tree -H . -I 'index.html' -D --timefmt='%b %d %Y %R' --charset utf-8 -T 'mit-notes' > dist/index.html
  deploy:
    permissions: 
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5 
        with: 
          folder: dist 
